### ISSUE TITLE
The user does not remain authenticated on the site

### ISSUE THREAD

**Issue by BaxAndrei** [crater-invoice/crater#649]
**Describe the bug**
The user does not remain authenticated on the site. As soon as I close all the active tabs (those that refer to the site where the script is installed) or the browser.

**Expected behavior**
Remain authenticated exactly as it was before the last update.

**Screenshots**
-

**Please complete the following information:**
- Crater version: 5.0.4
- PHP version: 7.4.26
- Database type and version: 5.7.34 - MySQL Community Server (GPL)

**Optional info**
- OS:  Windows 11 21H1
- Browser: Google Chrome | 96.0.4664.45 (Official Build) (64-bit)

**Comment by mohitpanjwani** [comment]
Hey, I think the issue is that it does not automatically redirect you back to dashboard if you're logged in when you open the root domain. 

Can you please check if you remain authenticated if you try to open `crater.test/admin/dashboard` instead of `crater.test` after closing the browser and reopening the site?

**Comment by BaxAndrei** [comment]
Hey. I checked, it doesn't seem to redirect me automatically. Thank you.

**Comment by BaxAndrei** [comment]
The bug is no longer present in the latest version.
