### ISSUE TITLE
Missing invoice reference number ({INVOICE_REF_NUMBER})

### ISSUE THREAD

**Issue by pszucs** [crater-invoice/crater#654]
**Describe the bug**
I have a 'Note' called 'Payment info' that I add to every invoice. This note has a field called {INVOICE_REF_NUMBER}. When creating / editing an invoice there's no input field to provide the value of this. This used to work in v4.20.

**Expected behavior**
I expected to see an input field on the create / edit invoice page titled something like 'Invoice ref number' (I can't remember what was it called in earlier versions of the app).

**Screenshots**
![Screenshot from 2021-12-13 11-31-45](https://user-images.githubusercontent.com/2471046/145805257-71f4cf2d-f10b-4b47-bab9-4baf3ca229c0.png)

**Please complete the following information:**
- Crater version: 5.0.6
- PHP version: 7.4
- Database type and version: MySQL 8.0.17

**Optional info**
- OS:  elementary OS
- Browser: Firefox

**Comment by mohitpanjwani** [comment]
Hey @pszucs, 

We removed the field from display because I think it was added before custom fields and I personally never really used it. 
Do you use that often? 

I'd argue that, custom fields might be better for this kind of think instead of a default field. Another solution would be to create a migration so it creates a custom field for invoices/estimates automatically and copies the value. 

Would that work for you?

**Comment by mohitpanjwani** [comment]
Let me know what you think @pszucs :) 

We'll consider adding this back if more people use this. Otherwise we could go with the solution that I mentioned so you can continue using this without issues. 

I can add the migration to the next minor release.

**Comment by pszucs** [comment]
Hi @mohitpanjwani ,

Thanks for your quick reply. I've looked at the new customization settings and I can confirm I can do what I wanted (which is to include a customer reference in the invoice reference number), thanks!

I just wasn't sure if the removal of the field was intentional or not as I couldn't find it in the release notes so I thought it might be a bug.
