### ISSUE TITLE
Sign up confirmation email blocked by spamcop

### ISSUE THREAD

**Issue by Akronae** [crater-invoice/crater#965]
**Describe the bug**
Sign up confirmation emails are being blocked by by spamcop on my mail server.

**Expected behavior**
The email to be delivered

**Screenshots**
```
Jun 18 04:16:00 mail postfix/smtpd[3652090]: NOQUEUE: reject: RCPT from wrqvnntq.outbound-mail.sendgrid.net[149.72.34.116]: 554 5.7.1 Service unavailable; Client host [149.72.34.116] blocked using bl.spamcop.net; Blocked - see https://www.spamcop.net/bl.shtml?149.72.34.116; from=<bounces+12907072-c18a-alexandre=daubricourt.com@em5507.craterapp.com> to=<alexandre@daubricourt.com> proto=ESMTP helo=<wrqvnntq.outbound-mail.sendgrid.net>
Jun 18 04:17:29 mail postfix/smtpd[3652090]: NOQUEUE: reject: RCPT from wrqvnnhc.outbound-mail.sendgrid.net[149.72.34.12]: 554 5.7.1 Service unavailable; Client host [149.72.34.12] blocked using bl.spamcop.net; Blocked - see https://www.spamcop.net/bl.shtml?149.72.34.12; from=<bounces+12907072-c18a-alexandre=daubricourt.com@em5507.craterapp.com> to=<alexandre@daubricourt.com> proto=ESMTP helo=<wrqvnnhc.outbound-mail.sendgrid.net>
```

I would suggest you not to use SendGrid as they use shared IPs used by a bunch of spammers, your emails will then be blocked for a lot customers. You can run a cheap custom and optimized mail server with something like [docker-mailserver](https://github.com/docker-mailserver/docker-mailserver)

**Comment by chestnutbak** [comment]
What sign up email?

**Comment by rihards-simanovics** [comment]
@Akronae, what you are describing here does not appear to be an issue with the software but instead with SendGrid. As you pointed out yourself, by providing the mail server log, is that the email technically was received, but was rejected by your mail server spam-assist, therefore, I would kindly ask you to close this issue and reach out SendGrid support directly.

If my memory serves me well, shared IPs are only part of free tier, you can upgrade to get a dedicated IPv4 an IPv6 addresses. your other alternative is to (as you already said) either run your own simple mail server or use SMPT to and a known email address to not land in spam.

**Comment by Akronae** [comment]
Clearly that is not code related but rather project related I thought you might want to hear about this issue here.
Closing.

**Comment by rihards-simanovics** [comment]
@Akronae, again, what you are describing is not an issue, your server rejected the email because the mail server's shared IP is blacklisted.

It was blacklisted because it was caught by Spam Cop trap address.

SendGrid has **paid tiers** that allow you to have **dedicated IP addresses**, again, if your emails are not going through, you need to contact SendGrid and request that they investigate it or pay SendGrid for a premium plan to get a dedicated IP where you know for sure no one else is influencing the IP trust rating.

It is really as simple as that, no point whining about unpleasant experience with a free tier of the service.

![image](https://user-images.githubusercontent.com/52106095/176397701-c0fa843e-dc39-4cb1-85da-f796eb4f7cd3.png)
![image](https://user-images.githubusercontent.com/52106095/176398242-c993ca0f-b04d-4080-9f58-8131f2819629.png)
